### ISSUE TITLE
Input File Documentation

### ISSUE THREAD

**Issue by LeeBergstrand** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#29]
Usage:   BackBLAST.py <queryGeneList.faa> <queryBLASTDB.faa>   <subjectBLASTDB.faa>

Query and subject BLAST DB are straight forward, but what is the queryGeneList.faa? 
If I have about 100 protein *.faa files in my query, would "queryGeneList.faa" be a concatenated file of these 100 *.fa files?

Thanks, Chris

_Originally posted by @tvtv195 in https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/issues/8#issuecomment-448463785_

**Comment by LeeBergstrand** [comment]
@tvtv195 Yes the list of query gene files should be concatenated together.

```cat *.faa >  queryGeneList.faa```

Usage: BackBLAST.py <queryGeneList.faa> <queryBLASTDB.faa> <subjectBLASTDB.faa>

| File 	| Description 	|
|--------------------	|-----------------------------------------------------------------------------------------------------------------------	|
| queryGeneList.faa 	| List of proteins from the query genome. For example, a FASTA files containing pathway genes from a reference organism 	|
| queryBLASTDB.faa 	| List of all proteins found in the reference organism's proteome.  	|
| subjectBLASTDB.faa 	| List of all proteins found in the target organisms's proteome. 	|

**Comment by LeeBergstrand** [comment]
@tvtv195 Any questions?

**Comment by tvtv195** [comment]
Great, thanks I'll try out your script then.
Also I was wondering, did you use it in a publication already?
Cheers,
Chris

**Comment by LeeBergstrand** [comment]
@tvtv195 BackBLAST was used in the following publications:

- Delineation of Steroid-Degrading Microorganisms through Comparative Genomic Analysis
DOI: [10.1128/mBio.00166-16](https://www.doi.org/10.1128/mBio.00166-16)
- Metagenomes Reveal Global Distribution of Bacterial Steroid Catabolism in Natural, Engineered, and Host Environments
DOI: [10.1128/mBio.02345-17](https://www.doi.org/10.1128/mBio.02345-17)

@jmtsuji and I are also working on a version two of BackBLAST (on the develop branch) that is updated and easier to use. We might release a standalone publication for version two.

**Comment by tvtv195** [comment]
Perfect thanks. I'll check them out and please keep me in the loop about
version 2.
