### ISSUE TITLE
Incorrect variable types

### ISSUE THREAD

**Issue by jmtsuji** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#31]
## Problem description
When using the current develop branch version of `BackBLAST.py` (commit ff96e60), I find that sometimes the best hits are filtered out. I noticed this when BLAST'ing query sequences to their own reference sequence as a control. One would expect all queries to return with 100% matches.

This works with default settings. For example, the query (10 genes),
```
BackBLAST.py --gene_cluster C_ferrooxidans_genes.faa --query_proteome C_ferrooxidans_ORFs.faa --subject_proteome C_ferrooxidans_ORFs.faa
```
Results in all 10 genes with 100% identity to themselves in the genome.

However, when adding the `--min_ident` flag, suddenly results start to disappear! All 100% match entries vanish, and the next closest hits are shown.

## Proposed solution
The problem seems to resolve when clearly specifying that `--min_ident` is a number (line ~188, start of the `main` function):

Old:
```
    input_e_value_cutoff = args.e_value
    input_min_ident_cutoff = args.min_ident
```

New:
```
    input_e_value_cutoff = args.e_value
    input_min_ident_cutoff = float(args.min_ident)
```

Suddenly, everything seems to work. Is it possible that `--min_ident` was being treated as a character for some reason?

## Things to consider
Should `--e_value` and other input flags also be clearly specified for their variable type?

@LeeBergstrand  I can make a PR for this if helpful.

Jackson

**Comment by jmtsuji** [comment]
Made pull request -- see #32

**Comment by LeeBergstrand** [comment]
https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/pull/32 Closed and merged.
