### ISSUE TITLE
Unusual behaviour in BackBLAST.py when run in multiple instances

### ISSUE THREAD

**Issue by jmtsuji** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#34]
@LeeBergstrand This is a bit of a mystery to me.

# Background
`BackBLAST.py` runs with 1 thread. In the snakemake workflow, I allow the user to run multiple instances of `BackBLAST.py` at a time (via the snakemake `--jobs` flag) to perform analyses in parallel.

# Problem description
When `--jobs` is 1 (i.e., 1 process runs at a time), pipeline results match what I'd expect. For example:
![BackBLAST_heatmap_1thread](https://user-images.githubusercontent.com/18713012/62598731-50c39900-b8b8-11e9-93c5-51e1f8fd6e71.png)

This figure is reproducible over multiple runs.

However, when `--jobs` is > 1, I get different result each time. Here are three runs with identical settings run with `--jobs 4` (i.e., 4 single-threaded processes can run at once):
![BackBLAST_heatmap_4jobs_run1](https://user-images.githubusercontent.com/18713012/62599085-3fc75780-b8b9-11e9-9732-033686404b0e.png)
![BackBLAST_heatmap_4jobs_run2](https://user-images.githubusercontent.com/18713012/62599115-58377200-b8b9-11e9-89fe-cad7b387acb2.png)
![BackBLAST_heatmap_4jobs_run4](https://user-images.githubusercontent.com/18713012/62599796-2c1cf080-b8bb-11e9-93d5-9c02f2337a71.png)

Specifically, it appears that **some genomes randomly have empty results from `BackBLAST.py`**. `BackBLAST.py` successfully ran (i.e., the log file looks fine), but the output file is empty.

Any idea what could be behind this issue (or keywords to look up)? Thanks.

**Comment by jmtsuji** [comment]
@LeeBergstrand Just had a brainwave. I haven't tested this yet, but it's probably the `tempQuery.faa` file generated when `BackBLAST.py` runs. There would be a file collision of two `tempQuery.faa` files when two simultaneous instances of `BackBLAST.py` run in the same folder at the same time.

Are you okay if I modify `BackBLAST.py` so that it adds a random string at the end of the `tempQuery.faa` filename to avoid the collision?

**Comment by LeeBergstrand** [comment]
Yes! I agree that’s what I thought it was. That should work.

**Comment by LeeBergstrand** [comment]
@jmtsuji  You might be able to use one subject file name + temp.faa or something like that as each temp file should be unique to each subject.

**Comment by jmtsuji** [comment]
@LeeBergstrand PR created that addresses this issue. I used the thread identifier to make each temp filename unique. I worry that the subject file name might still result in a collision one day (e.g., if we eventually add support for multiple query files). The temp filename is specified in the logfile so that it can be traced to a specific run during debugging, if needed.

**Comment by jmtsuji** [comment]
P.S. I've tested this fix, and it solves the problem. Now getting reproducible results!
