### ISSUE TITLE
Using thread number in temp_query may not be HPC safe.

### ISSUE THREAD

**Issue by LeeBergstrand** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#38]
@jmtsuji  With regards to https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/pull/36

That should work. However, if Snakemake is used in HPC mode with a Job queuing system its possible that thread A on machine X might have the same thread number as thread B on machine Y. If these machines are sharing disk (as would be the case in HPC) then their files could clober each other. Maybe replace the thread number with something like a UUID? https://docs.python.org/3.7/library/uuid.html

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks for the info -- will take a look.

**Comment by jmtsuji** [comment]
Changed to UUID. Thanks for the tip.
