### ISSUE TITLE
Best practice for BackBLAST conda install

### ISSUE THREAD

**Issue by jmtsuji** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#42]
I'm trying to decide the best way to organize BackBLAST as a conda package.

In my mind, BackBLAST has two major code components:
- `BackBLAST.sh` (command-line interface) and the snakemake workflow
- the BackBLAST `scripts` for individual steps in the snakemake workflow. Recall that the snakemake workflow currently creates conda envs with the dependencies needed to run these scripts.

We can either install these components together or separately. Here are two different scenarios I've thought of:
1. Make the BackBLAST conda package so that it includes `BackBLAST.sh` and all of the support scripts. This means that many dependencies (e.g., R) will be installed when installing BackBLAST itself.

2. Make the BackBLAST conda package so that it includes `BackBLAST.sh` (and the Snakefile) only. This would be a very simple install. I would then create a second conda package (e.g., `BackBLAST-utils`) with the support scripts and dependencies; this second conda package would be installed and run during the snakemake workflow.

@LeeBergstrand Any preferences? I lean toward the second option to keep things modular, in case we continue to expand the pipeline and need additional conda envs in the future. (FYI, this is not a high priority issue if you are busy currently.)

**Comment by LeeBergstrand** [comment]
@jmtsuji Do you anticipate adding a GUI to BackBLAST? If the whole thing is command line, then I would take the first approach of having everything in one Conda install. The only way I could see using two packages is if the utils software package is used for another application outside of BackBLAST (for example, some web app) that doesn't use snake make. Overall, I would take the first approach from simplicity. If we need to make a utils package at a later date, I don't anticipate it being very hard.

**Comment by LeeBergstrand** [comment]
@jmtsuji https://martinfowler.com/bliki/Yagni.html

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks for the link about yagni. Sure, I am okay going with a single conda install. I've structured the repo in #44 in preparation for having a single conda environment to contain BackBLAST, the utility scripts, and all dependencies.
