### ISSUE TITLE
Unneeded files in BackBLAST

### ISSUE THREAD

**Issue by jmtsuji** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#46]
Many files in BackBLAST1 have been deleted in BackBLAST2. Specifically:

![BackBLAST1](https://user-images.githubusercontent.com/18713012/64470416-dc775200-d110-11e9-8dc6-e9737befa1c1.png)

- Example files in `ExampleData`
- All scripts in `SupplementaryScripts`
- All scripts in `Statistics`
- Some scripts in `Visualization`

@LeeBergstrand Do you want to save some of these files (especially scripts) for another purpose? If so, you might want to move them over to another repo, for example.

Note that we will likely need to clean up this repo at some point due to the large repo size currently, so some of these files might disappear entirely from the git commit history in this repo. More on this in #47.

**Comment by LeeBergstrand** [comment]
@jmtsuji Addressed in https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/issues/47
